import { object } from "yup";

export default Object.freeze({
  HOME: "Home",
  LOGIN: "Login",
  MY_ADDRESS: "MyAddresses",
  MY_ORDERS: "MyOrders",
  CART: "Cart",
  CARD: "Card",
  LIST_ITEM_SEARCH: "ListItemSearch",
  OFFERSTAB: "OfferTab",
  MOBILETAB: "MobileTab",
  MOBILE_ACCESSORIES: "MobileAccessories",
  GROOMING_PRODUCTS: "GroomingProducts",
  BATH_BODY: "BathBody",
  HAIR_CARE: "HairCare",
  PRIVATE_POLICY: "PrivacyPolicy",
  NEED_HELP: "NeedHelp",
  TERMS_AND_CONDITION: "TermsAndCondition",
  CONTACT_US: "ContactUs",
  ABOUTUS: "AboutUs",
  LOGOUT: "Logout",
  PTC: "PTC",
  PTC_ADDRESS_TIME: "PTC_AddressTime",
  PTC_PLACE_ORDER: "PTC_PlaceOrder",
  CASH_ON_DELIVERY: "CashOnDelivery",
  EASYPAISA: "EasyPaisa",
  JAZZ_CASH_MOBILE: "JazzCashMobile",
  VIEWDETAILS: "ViewDetails",
});
